[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

"""
body = """
{% if version %}## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | default(value=now()) | date(format="%Y-%m-%d") }}{% else %}## [Unreleased]{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}

### {{ group | title }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first }}
{%- endfor %}
{% endfor %}

"""
trim = true

[git]
tag_pattern = "v[0-9].*"
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^Merge", skip = true },
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^refactor", group = "Changed" },
    { message = "^perf", group = "Changed" },
    { message = "^test", group = "Changed" },
    { message = "^docs", group = "Changed" },
    { message = "^style", group = "Changed" },
    { message = "^ci", group = "Changed" },
    { message = "^chore", group = "Changed" },
]
filter_commits = true
